#!/bin/bash
# Show a fuzzy-finder TUI for picking new packages to install (official + AUR).

preview_cmd='if pacman -Si {1} &>/dev/null; then pacman -Si {1}; else yay -Siia {1}; fi'
pkgbuild_cmd='yay -Gpa {1} | tail -n +5'

fzf_args=(
  --multi
  --preview "$preview_cmd"
  --preview-label='alt-p: toggle description, alt-b/B: toggle PKGBUILD, alt-j/k: scroll, tab: multi-select'
  --preview-label-pos='bottom'
  --preview-window 'down:65%:wrap'
  --bind 'alt-p:toggle-preview'
  --bind 'alt-d:preview-half-page-down,alt-u:preview-half-page-up'
  --bind 'alt-k:preview-up,alt-j:preview-down'
  --bind "alt-b:change-preview:$pkgbuild_cmd"
  --bind "alt-B:change-preview:$preview_cmd"
  --color 'pointer:green,marker:green'
)
pkg_names=$(yay -Slq | fzf "${fzf_args[@]}")
if [[ -n $pkg_names ]]; then
  echo "$pkg_names" | tr '\n' ' ' | xargs yay -S --noconfirm
fi
