#!/bin/sh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGINS_COMMON_DIR="$CONFIG_DIR/plugins-common"
PLUGINS_LAPTOP_DIR="$CONFIG_DIR/plugins-laptop"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

### Default settings ###
sketchybar --bar \
  height=38 \
  color=0x00000000 \
  margin=0 \
  sticky=on \
  padding_left=13 \
  padding_right=13 \
  notch_width=192 \
  display=main

sketchybar --default \
  background.color=0x66494d64 \
  background.corner_radius=5 \
  background.padding_right=5 \
  background.height=26 \
  icon.font="$FONT_FACE:Medium:15.0" \
  icon.padding_left=5 \
  icon.padding_right=5 \
  label.font="$FONT_FACE:Medium:12.0" \
  label.color=0xffcdd6f4 \
  label.y_offset=0 \
  label.padding_left=0 \
  label.padding_right=5

### Left ###
# Aerospace workspaces
sketchybar --add event aerospace_workspace_change

# Temporary order fix before aerospace offically support custom workspace order
# https://github.com/nikitabobko/AeroSpace/issues/999
workspaces=$(aerospace list-workspaces --all)
reorded_workspaces="U $(echo "$workspaces" | tr -d 'U')"

for sid in $reorded_workspaces; do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=0xfffab387 \
    icon.color=0xff1e1e2e \
    label.drawing=off \
    background.drawing=off \
    click_script="aerospace workspace $sid" \
    script="$PLUGINS_COMMON_DIR/aerospace.sh $sid"
done
sketchybar --add bracket spaces '/space\..*/' \
  --set spaces background.padding_right=100

# Gap
sketchybar --add item gap1 left \
  --set gap1 width=5 background.drawing=off

# Front app
sketchybar --add item front_app left \
  --set front_app \
  background.color=0xffa6e3a1 \
  background.padding_left=0 \
  background.padding_right=0 \
  icon.y_offset=1 \
  icon.color=0xff1e1e2e \
  label.drawing=no \
  script="$PLUGINS_COMMON_DIR/front_app.sh" \
  --add item front_app.separator left \
  --set front_app.separator \
  background.color=0x00000000 \
  background.padding_left=-3 \
  icon= \
  icon.color=0xffa6e3a1 \
  icon.font="$FONT_FACE:Bold:20.0" \
  icon.padding_left=0 \
  icon.padding_right=0 \
  icon.y_offset=1 \
  label.drawing=no \
  --add item front_app.name left \
  --set front_app.name \
  background.color=0x00000000 \
  background.padding_right=0 \
  icon.drawing=off \
  label.font="$FONT_FACE:Bold:12.0" \
  label.drawing=yes

sketchybar --add bracket front_app_bracket \
  front_app \
  front_app.separator \
  front_app.name \
  --subscribe front_app front_app_switched

### Left side of notch ###
# Memory Usage
sketchybar --add item memory q \
  --set memory \
  background.padding_right=0 \
  label.font="$FONT_FACE:Bold:12" \
  icon="󰘚" \
  icon.font="$FONT_FACE:Bold:16.0" \
  icon.color="0xffa6e3a1" \
  update_freq=15 \
  script="$PLUGINS_COMMON_DIR/ram.sh"

# CPU Usage
sketchybar --add item cpu.percent q \
  --set cpu.percent \
  label.font="$FONT_FACE:Bold:12" \
  label=CPU% \
  icon="" \
  icon.color="0xff89b4fa" \
  update_freq=3 \
  script="$PLUGINS_COMMON_DIR/cpu.sh"

# Gap
sketchybar --add item gap2 q \
  --set gap2 width=5 background.drawing=off

# Network speed
sketchybar --add item network.down q \
  --set network.down \
  background.drawing=off \
  y_offset=-7 \
  label.font="$FONT_FACE:Bold:10" \
  label.padding_right=0 \
  icon="" \
  icon.font="$FONT_FACE:Bold:16.0" \
  icon.color="0xff89b4fa" \
  icon.highlight_color="0xffa6e3a1" \
  update_freq=1

sketchybar --add item network.up q \
  --set network.up \
  background.padding_right=-64 \
  background.drawing=off \
  y_offset=7 \
  label.font="$FONT_FACE:Bold:10" \
  label.padding_right=0 \
  icon="" \
  icon.font="$FONT_FACE:Bold:16.0" \
  icon.color="0xff89b4fa" \
  icon.highlight_color="0xffa6e3a1" \
  update_freq=1 \
  script="$PLUGINS_COMMON_DIR/network.sh"

sketchybar --add bracket network_bracket \
  network.down \
  network.up

### Right side of notch ###
# Spotify
sketchybar --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify e \
  --set spotify \
  icon= \
  icon.y_offset=1 \
  icon.font="$FONT_FACE:Bold:20.0" \
  label.drawing=off \
  label.padding_left=3 \
  script="$PLUGINS_COMMON_DIR/spotify.sh" \
  --subscribe spotify spotify_change mouse.clicked

### Right ###
# Clock
sketchybar --add item clock right \
  --set clock \
  icon=󰃰 \
  icon.color=0xfff38ba8 \
  update_freq=10 \
  script="$PLUGINS_COMMON_DIR/clock.sh"

# Battery
sketchybar --add item battery right \
  --set battery \
  update_freq=20 \
  script="$PLUGINS_LAPTOP_DIR/battery.sh"

# Volume
sketchybar --add item volume right \
  --set volume \
  icon.color=0xff89b4fa \
  label.drawing=true \
  script="$PLUGINS_COMMON_DIR/volume.sh" \
  --subscribe volume volume_change

# update
sketchybar --update
